### ISSUE TITLE
Taxonomy data not found 

### ISSUE THREAD

**Issue by btredcup** [apcamargo/ictv-mmseqs2-protein-database#3]
Hi, 

Thanks for great tool. I am having an issue with taxonkit, I have downgraded it to v.0.11.1.

This is the error I am receiving after running ````taxonkit create-taxdump````:
````
[ERRO] taxonomy data not found, please download and uncompress ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz, and copy "names.dmp", "nodes.dmp", "delnodes.dmp", and "merged.dmp" to /home/users/.taxonkit
````

Any help would be greatly appreciated. Thanks

**Comment by apcamargo** [comment]
`taxonkit` needs you to have a taxdump in your home. Just download it from the link in this error message and copy the files to `~/.taxonkit`.

**Comment by btredcup** [comment]
That worked, thank you. 
Is that the same as the next step in the tutorial? 
````
# Download the NCBI taxdump
aria2c -x 4 "ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz"
mkdir ncbi-taxdump
tar zxfv taxdump.tar.gz -C ncbi-taxdump
rm taxdump.tar.gz
````

Or do I need to download it again and put it in ````ncbi-taxdump````?

**Comment by apcamargo** [comment]
I think you can skip it, as long as you point to the right directory in this command:
```bash
awk '{print $2}' prot.accession2taxid.FULL \
    | sort -u \
    | taxonkit --data-dir ncbi-taxdump lineage \
    | rg "\tViruses;" \
    | awk '{print $1}' \
    > virus_taxid.list
```

**Comment by btredcup** [comment]
Thank you.
Do I direct it to the ./taxonkit directory I downloaded the taxdump.tar.gz into initially? Or ictv-taxdump directory generated after running fix_taxdump.py?

**Comment by apcamargo** [comment]
`ncbi-taxdump` is the one you download from NCBI. The one you generate is the `ictv-taxdump`

**Comment by btredcup** [comment]
Okay, thank you. All sorted now
