### ISSUE TITLE
An issue related to create-taxdump command

### ISSUE THREAD

**Issue by njhhero** [apcamargo/ictv-mmseqs2-protein-database#5]
Thanks for sharing!
When I attempt to run this command:

taxonkit create-taxdump -K 1 -P 3 -C 5 -O 7 -F 9 -G 11 -S 13 -T 15 \
    --rank-names "realm","kingdom","phylum","class","order","family","genus","species" \
    ictv.taxonomy.tsv --out-dir ictv-taxdump

It reminds me that -K is an unknown flag(also -P -C etc.). Is this problem related with taxonkit version? 
Looking forward to your reply, great thanks!

**Comment by apcamargo** [comment]
Yes, this is a problem with TaxonKit's version. Try version [0.11.1](https://github.com/shenwei356/taxonkit/releases/tag/v0.11.1).

I recommend using [geNomad](https://github.com/apcamargo/genomad) for taxonomic assignment. I created this repo for testing purposes and I haven't benchmarked how good the assignment actually is.
